export const DATA_TEMPLATE = [
  {
    id: 1,
    first_name: "Shelby",
    last_name: "Breckon",
    email: "sbreckon0@list-manage.com",
    gender: "Male",
    ip_address: "93.49.24.210",
  },
  {
    id: 2,
    first_name: "Der",
    last_name: "Dome",
    email: "ddome1@baidu.com",
    gender: "Male",
    ip_address: "79.79.83.89",
  },
  {
    id: 3,
    first_name: "Vernice",
    last_name: "Seddon",
    email: "vseddon2@umn.edu",
    gender: "Female",
    ip_address: "238.198.164.127",
  },
  {
    id: 4,
    first_name: "Kora",
    last_name: "Pickin",
    email: "kpickin3@cloudflare.com",
    gender: "Female",
    ip_address: "111.35.101.143",
  },
  {
    id: 5,
    first_name: "Ase",
    last_name: "Geard",
    email: "ageard4@sitemeter.com",
    gender: "Male",
    ip_address: "22.24.44.59",
  },
  {
    id: 6,
    first_name: "Kristo",
    last_name: "Morrilly",
    email: "kmorrilly5@com.com",
    gender: "Male",
    ip_address: "190.135.167.183",
  },
  {
    id: 7,
    first_name: "Delaney",
    last_name: "Grigorushkin",
    email: "dgrigorushkin6@over-blog.com",
    gender: "Male",
    ip_address: "218.240.87.136",
  },
  {
    id: 8,
    first_name: "Kaylyn",
    last_name: "Akrigg",
    email: "kakrigg7@gmpg.org",
    gender: "Female",
    ip_address: "214.179.2.41",
  },
  {
    id: 9,
    first_name: "Deloris",
    last_name: "Curzey",
    email: "dcurzey8@latimes.com",
    gender: "Female",
    ip_address: "153.18.72.80",
  },
  {
    id: 10,
    first_name: "Heindrick",
    last_name: "Quilleash",
    email: "hquilleash9@sciencedaily.com",
    gender: "Male",
    ip_address: "72.31.34.211",
  },
  {
    id: 11,
    first_name: "Marc",
    last_name: "Martygin",
    email: "mmartygina@cmu.edu",
    gender: "Genderfluid",
    ip_address: "131.101.80.155",
  },
  {
    id: 12,
    first_name: "Milena",
    last_name: "Ruse",
    email: "mruseb@patch.com",
    gender: "Female",
    ip_address: "136.200.255.123",
  },
  {
    id: 13,
    first_name: "Brewer",
    last_name: "Hissett",
    email: "bhissettc@cornell.edu",
    gender: "Male",
    ip_address: "2.99.247.182",
  },
  {
    id: 14,
    first_name: "Lonnie",
    last_name: "Cogle",
    email: "lcogled@ft.com",
    gender: "Female",
    ip_address: "70.37.24.207",
  },
  {
    id: 15,
    first_name: "Hayyim",
    last_name: "de la Valette Parisot",
    email: "hdelavaletteparisote@blogs.com",
    gender: "Male",
    ip_address: "74.41.250.156",
  },
  {
    id: 16,
    first_name: "Roseanna",
    last_name: "Rhodef",
    email: "rrhodeff@360.cn",
    gender: "Female",
    ip_address: "17.151.58.224",
  },
  {
    id: 17,
    first_name: "Alva",
    last_name: "Lamba",
    email: "alambag@weibo.com",
    gender: "Male",
    ip_address: "97.148.111.88",
  },
  {
    id: 18,
    first_name: "Sabina",
    last_name: "Tallent",
    email: "stallenth@dion.ne.jp",
    gender: "Female",
    ip_address: "80.129.181.179",
  },
  {
    id: 19,
    first_name: "Phillip",
    last_name: "Jenking",
    email: "pjenkingi@example.com",
    gender: "Male",
    ip_address: "202.64.88.10",
  },
  {
    id: 20,
    first_name: "Isabeau",
    last_name: "McCumskay",
    email: "imccumskayj@cdc.gov",
    gender: "Female",
    ip_address: "214.16.179.205",
  },
];
